ALTER TYPE "BriefStatus" ADD VALUE 'INTERNAL_REVIEW';
ALTER TYPE "BriefStatus" ADD VALUE 'CLIENT_REVIEW';
ALTER TYPE "BriefStatus" ADD VALUE 'APPROVED';
ALTER TYPE "BriefStatus" ADD VALUE 'IN_PROGRESS';

ALTER TABLE "DiscoveryBrief"
ADD COLUMN "approvedBy" TEXT,
ADD COLUMN "approvedAt" TIMESTAMP(3);
